# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{zipit}
  s.version = "0.3.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alexander Shvets"]
  s.date = %q{2011-08-26}
  s.default_executable = %q{zipit}
  s.description = %q{Rake helper for zipping/unzipping project files.}
  s.email = %q{alexander.shvets@gmail.com}
  s.executables = ["zipit"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "CHANGES",
    "README",
    "Rakefile",
    "VERSION",
    "bin/zipit",
    "bin/zipit.bat",
    "lib/zipit.rb",
    "zipit.gemspec"
  ]
  s.homepage = %q{http://github.com/shvets/zipit}
  s.require_paths = ["lib"]
  s.requirements = ["none"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Rake helper for zipping/unzipping project files. (Summary).}
  s.test_files = [
    "spec/zipit_spec.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<zip>, [">= 0"])
      s.add_runtime_dependency(%q<rubyzip>, [">= 0.9.4"])
    else
      s.add_dependency(%q<zip>, [">= 0"])
      s.add_dependency(%q<rubyzip>, [">= 0.9.4"])
    end
  else
    s.add_dependency(%q<zip>, [">= 0"])
    s.add_dependency(%q<rubyzip>, [">= 0.9.4"])
  end
end

